name: Create ServiceNow Record

on:
  push:
    branches:
      - main

jobs:
  create-servicenow-record:
    runs-on: ubuntu-latest
    steps:
      - name: Create Incident in ServiceNow
        env:
          SERVICE_NOW_INSTANCE: ${{ secrets.SERVICE_NOW_INSTANCE }}
          SERVICE_NOW_USERNAME: ${{ secrets.SERVICE_NOW_USERNAME }}
          SERVICE_NOW_PASSWORD: ${{ secrets.SERVICE_NOW_PASSWORD }}
        run: |
          curl -X POST "https://${SERVICE_NOW_INSTANCE}.service-now.com/api/now/table/incident" \
          --user "${SERVICE_NOW_USERNAME}:${SERVICE_NOW_PASSWORD}" \
          --header "Accept:application/json" \
          --header "Content-Type:application/json" \
          --data '{"short_description": "This is a test incident created by GitHub Actions.","urgency":"2","impact":"2"}'
