name: Update and Order ServiceNow Catalog Item

on:
  push:
    branches:
      - main

jobs:
  update-and-order-catalog-item:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Read values from terraform.auto.tfvars
      id: readvars
      run: |
        echo "VM_COUNT=$(jq -r '.vm_count' terraform.auto.tfvars)" >> $GITHUB_ENV
        echo "VM_SIZE=$(jq -r '.vm_size' terraform.auto.tfvars)" >> $GITHUB_ENV
      shell: bash

    - name: Update and Order Catalog Item in ServiceNow
      run: |
        curl -X PATCH "https://${{ secrets.SERVICE_NOW_INSTANCE }}/api/now/table/catalog_item/a49a6bda970d42103671341e6253af33" \
             -u ${{ secrets.SERVICE_NOW_USERNAME }}:${{ secrets.SERVICE_NOW_PASSWORD }} \
             -H "Accept:application/json" \
             -H "Content-Type:application/json" \
             -d "{
                  \"vm_count\": \"${{ env.VM_COUNT }}\",
                  \"vm_size\": \"${{ env.VM_SIZE }}\"
                 }"
      env:
        SERVICENOW_INSTANCE: ${{ secrets.SERVICE_NOW_INSTANCE }}
        SERVICENOW_USERNAME: ${{ secrets.SERVICE_NOW_USERNAME }}
        SERVICENOW_PASSWORD: ${{ secrets.SERVICE_NOW_PASSWORD }}
